from ext import db, app
from models import Comment, Motherboard, CPU, GPU, CpuCooler, RAM, PSU, SSD, M2, CaseItem, Cooler, HDD, User,OrderItem,Order

with app.app_context():

    db.drop_all()
    db.create_all()

    admin = User(
        username="admin",
        password="adminpass",
        email="giuna.zh@gmail.com",
        image="",
        role="Admin"
    )
    z890 = Motherboard(
        name="ASUS ROG STRIX Z890-E GAMING WIFI",
        description="With an advanced power design and AI features, the ROG Strix Z890-E Gaming WiFi delivers top-tier performance. Equipped with Thunderbolt™ 4, WiFi 7, high-speed DDR5 slots, and seven M.2 slots, it provides exceptional connectivity and speed, making it ideal for elite gaming and advanced AI PC applications.",
        price=399.99,
        img="z890.jpg",
        img1="frontsidez890.png",
        img2="leftsidez890.jpg",
        img3="leftz890.jpg",
        img4="rightz890.jpg",
        brand="ASUS",
        brandimg="asus.png",
        socket="LGA 1851",
        chipset="Intel Z890",
        ram_type="DDR5",
        ram_slots="4",
        wifi="WiFi 7",
        motherboard_size="ATX",
        condition="New",
        stock=2,
    )
    x870 = Motherboard(
        name="GIGABYTE X870E AORUS PRO ICE AM5",
        description="GIGABYTE X870E AORUS PRO ICE AMD AM5 Motherboard, ATX, DDR5, 4X M.2, PCIe 5.0, USB4, WIFI7, 2.5GbE LAN, EZ-Latch",
        price=329.99,
        img="x870e.jpg",
        img1="x870front.png",
        img2="x870leeft.png",
        img3="x870left.webp",
        img4="x870right.webp",
        brand="GIGABYTE",
        brandimg="aorus.png",
        socket="AM5",
        chipset="X870",
        ram_type="DDR5",
        ram_slots="4",
        wifi="WiFi 7",
        motherboard_size="ATX",
        condition="New",
        stock=1,
    )
    z790 = Motherboard(
        name="MSI MPG Z790 EDGE WIFI LGA 1700",
        description="MSI MPG Z790 Edge WiFi Gaming Motherboard (Supports 12th/13th/14th Gen Intel Processors, LGA 1700, DDR5, PCIe 5.0, M.2, 2.5Gbps LAN, USB 3.2 Gen2, Wi-Fi 6E, Bluetooth 5.3, ATX)",
        price=371.23,
        img="z790.webp",
        img1="z790msifront.jpeg",
        img2="z790msileft.png",
        img3="z790msiright.jpg",
        img4="",
        brand="MSI",
        brandimg="msi.png",
        socket="LGA 1700",
        chipset="Intel Z790",
        ram_type="DDR5",
        ram_slots="4",
        wifi="WiFi 6E",
        motherboard_size="ATX",
        condition="New",
    )
    z590 = Motherboard(
        name="ASUS ROG Strix Z590-E Gaming WiFi 6E",
        description="Intel® Z590 LGA 1200 ATX motherboard with PCIe® 4.0, 14+2 Teamed power stages, Two-Way AI Noise-Cancelation, AI Overclocking, AI Cooling, AI Networking, WIFI 6E (802.11ax), Dual Intel® 2.5 Gb Ethernet, Quad M.2 with heatsinks, USB 3.2 Gen 2, SATA and AURA Sync RGB lighting",
        price=321.13,
        img="z590.webp",
        img1="z590rogleft.jpg",
        img2="z590rogfront.webp",
        img3="z590rogright.png",
        img4="",
        brand="ASUS",
        brandimg="asus.png",
        socket="LGA 1200",
        chipset="Intel Z590",
        ram_type="DDR4",
        ram_slots="4",
        wifi="WiFi 6E",
        motherboard_size="ATX",
        condition="New",
    )
    i72 = CPU(
        name="Intel Core i7-12700K",
        description="Intel Core i7-12700K Gaming Desktop Processor with Integrated Graphics and 12 (8P+4E) Cores up to 5.0 GHz Unlocked LGA1700 600 Series Chipset 125W",
        price=219.99,
        img="i7127k.webp",
        img1="i7127kfront.jpg",
        img2="i7127kback.jpg",
        img3="",
        img4="",
        brand="Intel",
        brandimg="intel.png",
        cpu_type="Desktop Processor",
        cpu_model="i7-12700K",
        socket="LGA 1700",
        cores_threads="12 (8P+4E) Cores / 20 Threads",
        integrated_graphics="Intel UHD Graphics 770",
        condition="New",
        stock=4,
    )
    r78 = CPU(
        name="Ryzen 7 7800X3D",
        description="AMD Ryzen 7 7800X3D 8-Core, 16-Thread Desktop Processor with 3D V-Cache Technology, Unlocked, 4.2 GHz Max Boost, AM5 Socket",
        price=329.99,
        img="r77800.webp",
        img1="",
        img2="",
        img3="",
        img4="",
        brand="AMD",
        brandimg="amd.png",
        cpu_type="Desktop Processor",
        cpu_model="Ryzen 7 7800X3D",
        socket="AM5",
        cores_threads="8 Cores / 16 Threads",
        integrated_graphics="Radeon Graphics",
        condition="New",
    )
    u9 = CPU(
        name="Intel Core Ultra 9 285K",
        description="Intel Core Ultra 9 285K Desktop Processor with Integrated Graphics and 16 (8P+8E) Cores up to 6.0 GHz Unlocked LGA1851 800 Series Chipset 125W",
        price=678.20,
        img="ultra.webp",
        img1="",
        img2="",
        img3="",
        img4="",
        brand="Intel",
        brandimg="intel.png",
        cpu_type="Desktop Processor",
        cpu_model="Core Ultra 9 285K",
        socket="LGA 1851",
        cores_threads="16 (8P+8E) Cores / 24 Threads",
        integrated_graphics="Intel UHD Graphics 770",
        condition="New",
    )
    r95 = CPU(
        name="Ryzen 9 9950X3D",
        description="AMD Ryzen 9 9950X3D 16-Core, 32-Thread Desktop Processor with 3D V-Cache Technology, Unlocked, 4.5 GHz Max Boost, AM5 Socket",
        price=679.95,
        img="r9.jpg",
        img1="r9995x3dfront.jpg",
        img2="",
        img3="",
        img4="",
        brand="AMD",
        brandimg="amd.png",
        cpu_type="Desktop Processor",
        cpu_model="Ryzen 9 9950X3D",
        socket="AM5",
        cores_threads="16 Cores / 32 Threads",
        integrated_graphics="Radeon Graphics",
        condition="New",
        stock=3,
    )
    r99 = CPU(
        name="Ryzen 9 9900X3D",
        description="AMD Ryzen 9 9900X3D 12-Core, 24-Thread Desktop Processor with 3D V-Cache Technology, Unlocked, 4.7 GHz Max Boost, AM5 Socket",
        price=718.62,
        img="r999x.webp",
        img1="r999x3dfront.jpg",
        img2="r999x3dback.png",
        img3="",
        img4="",
        brand="AMD",
        brandimg="amd.png",
        cpu_type="Desktop Processor",
        cpu_model="Ryzen 9 9900X3D",
        socket="AM5",
        cores_threads="12 Cores / 24 Threads",
        integrated_graphics="Radeon Graphics",
        condition="New",
        stock=2,
    )
    nzxtkraken = CpuCooler(
        name="NZXT Kraken 360mm - RL-KN360-B1",
        description="The NZXT Kraken 360mm (RL-KN360-B1) is a high-performance all-in-one (AIO) liquid CPU cooler designed for efficient heat dissipation and a sleek aesthetic. It combines powerful cooling capabilities with a customizable LCD display for personalization and real-time system monitoring.",
        price=179.99,
        img="nzxt.webp",
        img1="nzxt360front.webp",
        img2="",
        img3="",
        img4="",
        brand="NZXT",
        brandimg="nzxt.png",
        cooler_type="AIO Liquid Cooler",
        radiator_size="360mm",
        fan_size="120mm",
        noise_level="18-30 dBA",
        condition="New",
        stock=3,
    )
    tryxpano = CpuCooler(
        name="TRYX PANORAMA 360 360mm AIO",
        description="The TRYX PANORAMA 360 is an all-in-one (AIO) liquid CPU cooler designed to provide efficient cooling performance for high-performance processors. It features a 360mm radiator, three 120mm RGB fans, and a stylish design with customizable RGB lighting effects.",
        price=349.99,
        img="pano.jpg",
        img1="tryxpano360.jpg",
        img2="",
        img3="",
        img4="",
        brand="TRYX",
        brandimg="tryx.png",
        cooler_type="AIO Liquid Cooler",
        radiator_size="360mm",
        fan_size="120mm",
        noise_level="18-30 dBA",
        condition="New",
        stock=1,
    )
    corsair = RAM(
        name="CORSAIR Dominator Titanium 64GB (2 x 32GB)",
        description="CORSAIR DOMINATOR TITANIUM RGB 64GB-2X32GB 6600mhz DDR5",
        price=339.99,
        img="dominators.jpg",
        img1="dominatorleeft.jpg",
        img2="dominatorleft.png",
        img3="",
        img4="",
        brand="CORSAIR",
        brandimg="corsair.png",
        ram_type="DDR5",
        capacity="64GB (2 x 32GB)",
        speed="6600MHz",
        lighting="Yes",
        Color="gray",
        condition="New",
        stock=4,
    )
    team = RAM(
        name="Team T-Force Delta RGB DDR5 32GB (2X16GB) 6000MHZ",
        description="TEAMGROUP T-FORCE DELTA RGB DDR5 32GB (2X16GB) 6000MHZ",
        price=349.99,
        img="tforse.jpg",
        img1="deltaright.jpg",
        img2="",
        img3="",
        img4="",
        brand="TEAMGROUP",
        brandimg="teamgroup.png",
        ram_type="DDR5",
        capacity="32GB (2 x 16GB)",
        speed="6000MHz",
        lighting="Yes",
        Color="white",
        condition="New",
    )

    rog5090 = GPU(
        name="ASUS ROG Astral GeForce RTX 5090 32GB",
        description="ASUS ROG Astral GeForce RTX™ 5090 OC Edition Gaming Graphics Card (PCIe® 5.0, 32GB GDDR7, HDMI®/DP 2.1, 3.8-Slot, 4-Fan Design, Axial-tech Fans, Patented Vapor Chamber, Phase-Change GPU Thermal pad)",
        price=3359.99,
        img="5090.webp",
        img1="rogastralfront.png",
        img2="rogastralside.png",
        img3="rogastralback.png",
        img4="",
        brand="ASUS",
        brandimg="asus.png",
        gpu="RTX 5090",
        memory="32GB GDDR6X",
        numcoolers=3,
        Ports="HDMI, DisplayPort, USB-C",
        lighting = "Yes",
        color = "Black/Gray",
        condition = "New",
        stock=1,

    )
    rog4070 = GPU(
        name="ASUS ROG Strix GeForce RTX 4070 Ti SUPER OC Edition",
        description="ASUS ROG Strix GeForce RTX™ 4070 OC Edition Gaming Graphics Card (PCIe 4.0, 12GB GDDR6X, DLSS 3, HDMI 2.1, DisplayPort 1.4a)",
        price=1159.99,
        img="4070.webp",
        img1="",
        img2="",
        img3="",
        img4="",
        brand="ASUS",
        brandimg="asus.png",
        gpu="RTX 4070 Ti",
        memory="12GB GDDR6X",
        numcoolers=3,
        Ports="HDMI, DisplayPort",
        lighting = "Yes",
        color = "Gray/Red/Blue",
        condition = "New",
        stock=2,

    )
    evga3080 = GPU(
        name="EVGA GeForce RTX 3080 FTW3 ULTRA",
        description="EVGA GeForce RTX 3080 FTW3 Ultra Gaming, 10G-P5-3897-KL, 10GB GDDR6X, iCX3 Technology, ARGB LED, Metal Backplate, LHR",
        price=549.99,
        img="evga.webp",
        img1="",
        img2="",
        img3="",
        img4="",
        brand="EVGA",
        brandimg="evga.png",
        gpu="RTX 3080",
        memory="10GB GDDR6X",
        numcoolers=3,
        Ports="HDMI, DisplayPort",
        lighting = "Yes",
        color = "Black",
        condition = "New",
    )
    rx9070 = GPU(
        name="ASUS PRIME Radeon RX 9070 XT 16GB",
        description="ASUS Prime Radeon™ RX 9070 XT OC Edition Graphics Card (PCIe 5.0, HDMI/DP 2.1, 2.5-Slot Design, axial-tech Fans, Dual Ball Fan Bearings, Dual BIOS, ASUS GPU Guard)",
        price=1187.99,
        img="rx90.webp",
        img1="",
        img2="",
        img3="",
        img4="",
        brand="ASUS",
        brandimg="asus.png",
        gpu="RX 9070 XT",
        memory="16GB GDDR6",
        numcoolers=3,
        Ports="HDMI, DisplayPort",
        lighting = "No",
        color = "Black",
        condition = "New",
    )
    intel_arc = GPU(
        name="Intel Arc B580 Limited Edition Graphics Card",
        description="Intel Arc B580 Limited Edition Graphics Card, 8GB GDDR6, PCIe 4.0, Ray Tracing, XeSS, DirectX 12 Ultimate, HDMI 2.1, DisplayPort 2.0",
        price=379.00,
        img="intelarc.webp",
        img1="",
        img2="",
        img3="",
        img4="",
        brand="Intel",
        brandimg="intel.png",
        gpu="Arc B580",
        memory="12GB GDDR6",
        numcoolers=2,
        Ports="HDMI, DisplayPort",
        lighting = "No",
        color = "Black",
        condition = "New",
        stock=3,
    )

    RMx850 = PSU(
        name="CORSAIR RMx Series RM850e 850 W",
        description="CORSAIR RM850e (2025) Fully Modular Low-Noise ATX Power Supply with 12V-2x6 Cable – ATX 3.1 & PCIe 5.1 Compliant, Cybenetics Gold Efficiency, 105°C-Rated Capacitors, Modern Standby Mode – Black",
        price=113.99,
        img="850.jpg",
        img1="",
        img2="",
        img3="",
        img4="",
        brand="CORSAIR",
        brandimg="corsair.png",
        wattage="850W",
        efficiency="80 PLUS Gold",
        modular="Fully Modular",
        lighting="No",
        color="Black",
        condition="New",
    )
    lianli1000 = PSU(
        name="Lian Li Edge Serie - 1000W Full Modular",
        description="Lian Li Edge Series-1000W Full Modular Power Supply-80 Plus Platinum-ATX 3.0, 3.1-PCIE 5.1-L-Shape Design for Dual Chamber Case-120mm FDB Fan-Supports up to 4X USB Devices-Black (EG1000BE.US)",
        price=154.99,
        img="100wa.jpg",
        img1="100wafront.jpg",
        img2="",
        img3="",
        img4="",
        brand="Lian Li",
        brandimg="lianli.png",
        wattage="1000W",
        efficiency="80 PLUS Platinum",
        modular="Fully Modular",
        lighting="No",
        color="White",
        condition="New",
        stock=2,
    )
    asus1000 = PSU(
        name="ASUS ROG Strix 1000W Platinum",
        description="ASUS ROG Strix 1000W Platinum (Fully Modular Power Supply, 80 Plus Platinum Certified, ATX 3.1, Cybenetics Lambda A+, GaN MOSFET, GPU-First Intelligent Voltage Stabilizer, 10-Year Warranty)",
        price=229.99,
        img="asus1000.webp",
        img1="",
        img2="",
        img3="",
        img4="",
        brand="ASUS",
        brandimg="asus.png",
        wattage="1000W",
        efficiency="80 PLUS Platinum",
        modular="Fully Modular",
        lighting="No",
        color="Black",
        condition="New",
    )
    BarraCuda1000 = HDD(
        name="Seagate BarraCuda ST1000DM010 1TB",
        description="Seagate BarraCuda 1TB Internal Hard Drive HDD – 3.5 Inch SATA 6 Gb/s 7200 RPM 64MB Cache for PC Desktop Computer (ST1000DM010)",
        price=39.73,
        img="seagate.jpg",
        img1="",
        img2="",
        img3="",
        img4="",
        brand="Seagate",
        brandimg="seagate.png",
        capacity="1TB",
        rpm="7200 RPM",
        cache="64MB",
        interface="SATA 6 Gb/s",
        condition="New",
        stock=5,
    )
    ironwolf = HDD(
        name="Seagate IronWolf 4TB NAS Hard Drive 5900",
        description="Seagate IronWolf 4TB NAS Hard Drive 5900 RPM 128MB Cache for NAS Server (ST4000NE005)",
        price=154.99,
        img="ironwolf.jpg",
        img1="",
        img2="",
        img3="",
        img4="",
        brand="Seagate",
        brandimg="seagate.png",
        capacity="4TB",
        rpm="5900 RPM",
        cache="128MB",
        interface="SATA 6 Gb/s",
        condition="New",
        stock=4,
    )

    tforce = SSD(
        name="Team Group T-FORCE VULCAN Z 2.5' 1TB",
        description="Team Group T-FORCE VULCAN Z 2.5 Inch SATA III SSD 1TB - Up to 550 MB/s Read & 500 MB/s Write - TLCS-25A01T0C",
        price=47.99,
        img="ssd.webp",
        img1="",
        img2="",
        img3="",
        img4="",
        brand="TeamGroup",
        brandimg="teamgroup.png",
        capacity="1TB",
        read_speed="Up to 550 MB/s",
        write_speed="Up to 500 MB/s",
        interface="SATA III",
        condition="New",
        stock=2,
    )
    samsung870 = SSD(
        name="Samsung 870 EVO SATA III SSD 1TB",
        description="Samsung 870 EVO SATA III 2.5 Inch SSD 1TB - Up to 560 MB/s Read & 530 MB/s Write - MZ-77E1T0B/AM",
        price=79.99,
        img="smsngssd.webp",
        img1="",
        img2="",
        img3="",
        img4="",
        brand="Samsung",
        brandimg="samsung.png",
        capacity="1TB",
        read_speed="Up to 560 MB/s",
        write_speed="Up to 530 MB/s",
        interface="SATA III",
        condition="New",
        stock=4,
    )

    Furry = M2(
        name="Kingston FURY Renegade M.2 2280 1TB",
        description="Kingston FURY Renegade PCIe 4.0 NVMe M.2 2280 SSD 1TB - Up to 7300MB/s Read & 7000MB/s Write - Solid State Drive - SFYRS/1000G",
        price=115.39,
        img="furry.webp",
        img1="",
        img2="",
        img3="",
        img4="",
        brand="Kingston",
        brandimg="kingston.png",
        capacity="1TB",
        read_speed="Up to 7300 MB/s",
        write_speed="Up to 7000 MB/s",
        interface="PCIe 4.0 NVMe",
        condition="New",
        stock=2,
    )
    smsng990pro = M2(
        name="SAMSUNG SSD 990 PRO with Heatsink 2TB",
        description="SAMSUNG 990 PRO w/ Heatsink SSD 2TB, PCIe Gen4 M.2 2280 Internal Solid State Hard Drive, Seq. Read Speeds Up To 7,450MB/s for High End Computing, Workstations, Compatible w/ PlayStation 5, MZ-V9P2T0CW",
        price=149.99,
        img="990heat.webp",
        img1="",
        img2="",
        img3="",
        img4="",
        brand="Samsung",
        brandimg="samsung.png",
        capacity="2TB",
        read_speed="7,450MB/s",
        write_speed="6900 MB/s",
        interface="PCIe 4.0 NVMe",
        condition="New",
        stock=2,
    )
    smsng990evo_plus = M2(
        name="SAMSUNG 990 EVO PLUS SSD 4TB",
        description="Samsung 990 EVO Plus SSD 4TB, PCIe Gen 4x4 | Gen 5x2 M.2, Speeds Up-to 7,250 MB/s, Upgrade Storage for PC/Laptops, HMB Technology and Intelligent Turbowrite 2.0, (MZ-V9S4T0B/AM)",
        price=327.99,
        img="990evo.png",
        img1="",
        img2="",
        img3="",
        img4="",
        brand="Samsung",
        brandimg="samsung.png",
        capacity="4TB",
        read_speed="7,250MB/s",
        write_speed="6350 MB/s",
        interface="PCIe 4.0 NVMe",
        condition="New"
    )

    case = CaseItem(
        name="LIAN LI O11 vision compact white",
        description="Lian Li O11Vision Compact White-Steel-Tempered Glass ATX Mid Tower Computer Case-Back Connect Support-O11VPW",
        price=129.99,
        img="lianlio11.jpg",
        img1="",
        img2="",
        img3="",
        img4="",
        brand="Lian Li",
        brandimg="lianli.png",
        compatability="ATX, Micro ATX",
        casetype="Mid Tower",
        color="White",
        condition="New",
        stock=3,
    )
    nzxt_h9 = CaseItem(
        name="NZXT H9 Flow - All White",
        description="NZXT H9 Flow (2025) – Large Dual-Chamber ATX Mid-Tower Airflow PC Case – Includes 3 x 140mm & 1 x 120mm Fans – 420mm Radiator Support – Tempered Glass – Back-Connect Ready – White",
        price=149.99,
        img="h9flow.jpg",
        img1="",
        img2="",
        img3="",
        img4="",
        brand="NZXT",
        brandimg="nzxt.png",
        compatability="ATX",
        casetype="Mid Tower",
        color="White",
        condition="New",
        stock=2,
    )
    hyte_y70 = CaseItem(
        name="HYTE Y70 touch infinite Dual Chamber ATX",
        description="Hyte Y70 Touch Infinite Dual Chamber ATX Mid Tower Modern Aesthetic Case with Integrated 2.5K LCD Touchscreen - Panda/White",
        price=369.99,
        img="hytey70.jpg",
        img1="",
        img2="",
        img3="",
        img4="",
        brand="HYTE",
        brandimg="hyte.png",
        compatability="ATX",
        casetype="Mid Tower",
        color="White/Black",
        condition="New",
        stock=1,
    )

    fans = Cooler(
        name="LIAN LI UNI FAN SL INFINITY 120 RGB BLACK",
        description="LIAN LI UNI FAN SL-INF 120 RGB BLACK 1 PACK 120mm",
        price=29.99,
        img="infblack.webp",
        img1="",
        img2="",
        img3="",
        img4="",
        brand="Lian Li",
        brandimg="lianli.png",
        numoffans=1,
        size = "120mm",
        lighting = "Yes",
        color = "Black",
        condition = "New",
        stock=21,
    )
    fans_white = Cooler(
        name="LIAN LI UNI FAN SL INFINITY 120 RGB WHITE",
        description="LIAN LI UNI FAN SL-INF 120 RGB BLACK 1 PACK 120mm",
        price=32.99,
        img="infwhite.webp",
        img1="",
        img2="",
        img3="",
        img4="",
        brand="Lian Li",
        brandimg="lianli.png",
        numoffans=1,
        size = "120mm",
        lighting = "Yes",
        color = "White",
        condition = "New",
        stock=18,
    )

    db.session.add(admin)
    db.session.add(z890)
    db.session.add(x870)
    db.session.add(z790)
    db.session.add(z590)
    db.session.add(i72)
    db.session.add(r78)
    db.session.add(u9)
    db.session.add(r95)
    db.session.add(r99)
    db.session.add(nzxtkraken)
    db.session.add(tryxpano)
    db.session.add(corsair)
    db.session.add(team)
    db.session.add(rog5090)
    db.session.add(rog4070)
    db.session.add(evga3080)
    db.session.add(rx9070)
    db.session.add(intel_arc)
    db.session.add(RMx850)
    db.session.add(lianli1000)
    db.session.add(asus1000)
    db.session.add(BarraCuda1000)
    db.session.add(ironwolf)
    db.session.add(tforce)
    db.session.add(samsung870)
    db.session.add(Furry)
    db.session.add(smsng990pro)
    db.session.add(smsng990evo_plus)
    db.session.add(case)
    db.session.add(nzxt_h9)
    db.session.add(hyte_y70)
    db.session.add(fans)
    db.session.add(fans_white)
    db.session.commit()