"""Switch comments to motherboard-specific

Revision ID: 4b9d03998eee
Revises: dbbaad10c9e9
Create Date: 2026-01-03 15:59:50.988068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9d03998eee'
down_revision = 'dbbaad10c9e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coolers')
    op.drop_table('users')
    op.drop_table('cpucoolers')
    op.drop_table('m2s')
    op.drop_table('hdds')
    op.drop_table('cpus')
    op.drop_table('comments')
    op.drop_table('cases')
    op.drop_table('gpus')
    op.drop_table('ssds')
    op.drop_table('motherboards')
    op.drop_table('rams')
    op.drop_table('products')
    op.drop_table('psus')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psus',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('img', sa.VARCHAR(), nullable=True),
    sa.Column('brand', sa.VARCHAR(), nullable=True),
    sa.Column('brandimg', sa.VARCHAR(), nullable=True),
    sa.Column('wattage', sa.INTEGER(), nullable=True),
    sa.Column('efficiency', sa.VARCHAR(), nullable=True),
    sa.Column('modular', sa.VARCHAR(), nullable=True),
    sa.Column('lighting', sa.VARCHAR(), nullable=True),
    sa.Column('color', sa.VARCHAR(), nullable=True),
    sa.Column('condition', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('img', sa.VARCHAR(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rams',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('img', sa.VARCHAR(), nullable=True),
    sa.Column('brand', sa.VARCHAR(), nullable=True),
    sa.Column('brandimg', sa.VARCHAR(), nullable=True),
    sa.Column('ram_type', sa.VARCHAR(), nullable=True),
    sa.Column('capacity', sa.VARCHAR(), nullable=True),
    sa.Column('speed', sa.VARCHAR(), nullable=True),
    sa.Column('lighting', sa.VARCHAR(), nullable=True),
    sa.Column('Color', sa.VARCHAR(), nullable=True),
    sa.Column('condition', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motherboards',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('img', sa.VARCHAR(), nullable=True),
    sa.Column('brand', sa.VARCHAR(), nullable=True),
    sa.Column('brandimg', sa.VARCHAR(), nullable=True),
    sa.Column('socket', sa.VARCHAR(), nullable=True),
    sa.Column('chipset', sa.VARCHAR(), nullable=True),
    sa.Column('ram_type', sa.VARCHAR(), nullable=True),
    sa.Column('ram_slots', sa.VARCHAR(), nullable=True),
    sa.Column('wifi', sa.VARCHAR(), nullable=True),
    sa.Column('motherboard_size', sa.VARCHAR(), nullable=True),
    sa.Column('condition', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ssds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('img', sa.VARCHAR(), nullable=True),
    sa.Column('brand', sa.VARCHAR(), nullable=True),
    sa.Column('brandimg', sa.VARCHAR(), nullable=True),
    sa.Column('capacity', sa.VARCHAR(), nullable=True),
    sa.Column('read_speed', sa.VARCHAR(), nullable=True),
    sa.Column('write_speed', sa.VARCHAR(), nullable=True),
    sa.Column('interface', sa.VARCHAR(), nullable=True),
    sa.Column('condition', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gpus',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('img', sa.VARCHAR(), nullable=True),
    sa.Column('brand', sa.VARCHAR(), nullable=True),
    sa.Column('brandimg', sa.VARCHAR(), nullable=True),
    sa.Column('gpu', sa.VARCHAR(), nullable=True),
    sa.Column('memory', sa.VARCHAR(), nullable=True),
    sa.Column('numcoolers', sa.INTEGER(), nullable=True),
    sa.Column('Ports', sa.VARCHAR(), nullable=True),
    sa.Column('lighting', sa.VARCHAR(), nullable=True),
    sa.Column('color', sa.VARCHAR(), nullable=True),
    sa.Column('condition', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('img', sa.VARCHAR(), nullable=True),
    sa.Column('brand', sa.VARCHAR(), nullable=True),
    sa.Column('brandimg', sa.VARCHAR(), nullable=True),
    sa.Column('compatability', sa.VARCHAR(), nullable=True),
    sa.Column('casetype', sa.VARCHAR(), nullable=True),
    sa.Column('color', sa.VARCHAR(), nullable=True),
    sa.Column('condition', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('product_type', sa.VARCHAR(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cpus',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('img', sa.VARCHAR(), nullable=True),
    sa.Column('brand', sa.VARCHAR(), nullable=True),
    sa.Column('brandimg', sa.VARCHAR(), nullable=True),
    sa.Column('cpu_type', sa.VARCHAR(), nullable=True),
    sa.Column('cpu_model', sa.VARCHAR(), nullable=True),
    sa.Column('socket', sa.VARCHAR(), nullable=True),
    sa.Column('cores_threads', sa.VARCHAR(), nullable=True),
    sa.Column('integrated_graphics', sa.VARCHAR(), nullable=True),
    sa.Column('condition', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hdds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('img', sa.VARCHAR(), nullable=True),
    sa.Column('brand', sa.VARCHAR(), nullable=True),
    sa.Column('brandimg', sa.VARCHAR(), nullable=True),
    sa.Column('capacity', sa.VARCHAR(), nullable=True),
    sa.Column('rpm', sa.VARCHAR(), nullable=True),
    sa.Column('cache', sa.VARCHAR(), nullable=True),
    sa.Column('interface', sa.VARCHAR(), nullable=True),
    sa.Column('condition', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m2s',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('img', sa.VARCHAR(), nullable=True),
    sa.Column('brand', sa.VARCHAR(), nullable=True),
    sa.Column('brandimg', sa.VARCHAR(), nullable=True),
    sa.Column('capacity', sa.VARCHAR(), nullable=True),
    sa.Column('read_speed', sa.VARCHAR(), nullable=True),
    sa.Column('write_speed', sa.VARCHAR(), nullable=True),
    sa.Column('interface', sa.VARCHAR(), nullable=True),
    sa.Column('condition', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cpucoolers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('img', sa.VARCHAR(), nullable=True),
    sa.Column('brand', sa.VARCHAR(), nullable=True),
    sa.Column('brandimg', sa.VARCHAR(), nullable=True),
    sa.Column('cooler_type', sa.VARCHAR(), nullable=True),
    sa.Column('radiator_size', sa.VARCHAR(), nullable=True),
    sa.Column('fan_size', sa.VARCHAR(), nullable=True),
    sa.Column('noise_level', sa.VARCHAR(), nullable=True),
    sa.Column('condition', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('image', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('coolers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('img', sa.VARCHAR(), nullable=True),
    sa.Column('brand', sa.VARCHAR(), nullable=True),
    sa.Column('brandimg', sa.VARCHAR(), nullable=True),
    sa.Column('numoffans', sa.INTEGER(), nullable=True),
    sa.Column('size', sa.VARCHAR(), nullable=True),
    sa.Column('lighting', sa.VARCHAR(), nullable=True),
    sa.Column('color', sa.VARCHAR(), nullable=True),
    sa.Column('condition', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
